services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network

  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
